import type { NextPage } from "next";
import Head from "next/head";
import Edit from "../components/Edit";

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Edit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Edit page</h1>
      <main>
        <Edit />
      </main>
    </div>
  );
};

export default Home;
