import type { NextPage } from "next";
import Head from "next/head";
import FoodList from "../components/Food/FoodList";
import Input from "../components/BaseUI/Input";
import useFetch from "../hooks/useFetch";

const Home: NextPage = () => {
  const {
    data: foods,
    isLoading,
    error,
  } = useFetch("http://localhost:5000/foods");
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Food API</h1>
      <main>
        <Input type="number" />
        <FoodList foods={foods || []} />
      </main>
    </div>
  );
};

export default Home;
